[package]
name = "spooky-utils"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
env_logger.workspace = true
log.workspace = true
rustls-pki-types.workspace = true
