[package]
name = "spooky-edge"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
log.workspace = true
quiche.workspace = true
spooky-config = { path = "../config" }
