[package]
name = "spooky-edge"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
log.workspace = true
quiche.workspace = true
spooky-config = { path = "../config" }
spooky-lb = { path = "../lb" }
spooky-bridge = { path = "../bridge" }
spooky-transport = { path = "../transport" }
bytes.workspace = true
http.workspace = true
http-body-util.workspace = true
hyper.workspace = true
tokio.workspace = true

[dev-dependencies]
rand.workspace = true
rcgen = "0.12"
tempfile = "3"
bytes.workspace = true
http.workspace = true
http-body-util.workspace = true
hyper.workspace = true
hyper-util.workspace = true
tokio.workspace = true
